# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: ENVBase

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo "Where am I?"
    pwd
    echo "What is located here?"
    ls -la
    echo "What kind of OS is this?"
    uname -a
    echo "What release of OS is this?"
    cat /etc/os-release
    echo $(bwise-secret) > /tmp/bwise-secret.txt
    echo "BWISE secret from variable is $(bwise-secret)"
    echo "BWISE secret from file is"
    cat /tmp/bwise-secret.txt
    echo "BWISE secret file size is"
    ls -la /tmp/bwise-secret.txt
  displayName: 'Run a multi-line script'
