---

- hosts: localhost
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo


  tasks:
  - name: touch ansible_vault password file
    file:
      path: ~/.ansible_vault_key
      state: touch
      mode: 0600
