---

- hosts: localhost
  gather_facts: no
  vars:
    otherfile: "{{ lookup('env','otherfile') }}"
    datacenter: "{{ lookup('env','SRE_DC') }}"
    env_name: "{{ lookup('env','SRE_ENV') }}"
    ansible_user: "{{ lookup('env','ansible_user') }}"
    ansible_password: "{{ lookup('env','ansible_password') }}"
    nexus_username: "{{ lookup('env','nexus_username') }}"
    nexus_password: "{{ lookup('env','nexus_password') }}"
    ansible_vault_password_file: "{{ lookup('env','ANSIBLE_VAULT_PASSWORD_FILE') }}"


  tasks:
  - name: touch other file
    file:
      path: "~/{{ otherfile }}"
      state: touch
      mode: 0600
  - name: Run shell
    shell: |
      echo "Datacenter" >> /tmp/bwfoo.txt
      echo "{{ datacenter }}" >> /tmp/bwfoo.txt
      echo "Env name" >> /tmp/bwfoo.txt
      echo "{{ env_name }}" >> /tmp/bwfoo.txt
      echo "Ansible user" >> /tmp/bwfoo.txt
      echo "{{ ansible_user }}" >> /tmp/bwfoo.txt
      echo "Ansible password" >> /tmp/bwfoo.txt
      echo "{{ ansible_password }}" >> /tmp/bwfoo.txt
      echo "Nexus user" >> /tmp/bwfoo.txt
      echo "{{ nexus_username }}" >> /tmp/bwfoo.txt
      echo "Nexus password" >> /tmp/bwfoo.txt
      echo "{{ nexus_password }}" >> /tmp/bwfoo.txt
      echo "ANSIBLE_VAULT_PASSWORD_FILE" >> /tmp/bwfoo.txt
      echo "{{ ansible_vault_password_file }}" >> /tmp/bwfoo.txt
    args:
      executable: /usr/bin/bash